Update run

diff --git a/run b/run
--- a/run
+++ b/run
@@ -3,9 +3,6 @@
 # Fatorial 2^k install script for Ubuntu 18.04.1 Server LTS (Bionic Beaver)
 # Emerson Barea (emerson.barea@gmail.com)
 
-# Fail on error
-#set -e
-
 function welcome() {
     printf '\n%s\n' 'This script creates the complete environment for Factorial 2^k experiments.
                    Some requirements must be met:
@@ -18,19 +15,43 @@ function welcome() {
 
 function qtd_hosts() {
     printf '\n%s' 'Answer: how many cluster nodes will be created? (only number. Ex.: 10): '
-    read qtd_hosts
+    read var_qtd_hosts
 
-    # testing if "qtd_hosts" is a number
+    # testing if "var_qtd_hosts" is a number
     re='^[0-9]+$'
-    if ! [[ $qtd_hosts =~ $re ]] ; then
+    if ! [[ $var_qtd_hosts =~ $re ]] ; then
         printf '\e[1;31m%-6s\e[m' 'error: Write only numbers'
         qtd_hosts;
     fi
 }
 
-#function note() {
-#    printf '\n\e[1;32m%-6s\e[m\n' 'Note: At the end of the installation, this machine will be renamed to "node1".'
-#}
+function install_packages() {
+    function app_nps() {
+        printf '\n%s' 'Network Prototype Simulator (NPS) [y/n]: '
+        read var_app_nps
+
+        # testing if "var_app_nps" is y or n
+        if [ "$var_app_nps" != "Y" ] && [ "$var_app_nps" != "y" ] \
+        && [ "$var_app_nps" != "N" ] && [ "$var_app_nps" != "n" ]; then
+            printf '\e[1;31m%-6s\e[m' 'error: Press only Y|y or N|n'
+            app_nps;
+        fi
+    }
+    function app_maxinet() {
+        printf '\n%s' 'MaxiNet [y/n]: '
+        read var_app_maxinet
+
+        # testing if "app_maxinet" is y or n
+        if [ "$var_app_maxinet" != "Y" ] && [ "$var_app_maxinet" != "y" ] \
+        && [ "$var_app_maxinet" != "N" ] && [ "$var_app_maxinet" != "n" ]; then
+            printf '\e[1;31m%-6s\e[m' 'error: Press only Y|y or N|n'
+            app_maxinet;
+        fi
+    }
+    printf '\n%s' 'What application do you want to install?'
+    app_nps;
+    app_maxinet;
+}
 
 function update_SO_install_packages() {
     printf '\n\e[1;33m%-6s\e[m\n' '-- Initiating SO update and package install...'
@@ -71,7 +92,7 @@ function hosts_file() {
     printf '\e[1;33m%-6s\e[m\n' 'Erasing all previous configuration.'
     cp /dev/null /etc/hosts										# limpa arquivo hosts
     echo 127.0.0.1	localhost.localdomain	localhost > /etc/hosts					# cadastra loopback no arquivo hosts
-    for ((i=1; i<=$qtd_hosts; i++)); do echo 10.0.0.$i    node$i >> /etc/hosts; done
+    for ((i=1; i<=$var_qtd_hosts; i++)); do echo 10.0.0.$i    node$i >> /etc/hosts; done
     printf '\n%s\n' 'showing /etc/hosts'
     cat /etc/hosts
 }
@@ -86,8 +107,8 @@ function ssh_file() {
     sudo -u mininet ssh-keygen -t rsa -N "" -f /home/mininet/.ssh/id_rsa               			# gerando a chave ssh do usuário mininet
 
     printf '\n\e[1;33m%-6s\e[m\n' 'Adding the mininet user key in the authorized_keys'
-    for (( c=1; c<=$qtd_hosts; c++ )); do sudo -u mininet cat /home/mininet/.ssh/id_rsa.pub | \
-          sudo -u mininet tee --append /home/mininet/.ssh/authorized_keys; done                        	# adicionando a chave do usuário mininet no authorized_keys (qtd_hosts)
+    for (( c=1; c<=$var_qtd_hosts; c++ )); do sudo -u mininet cat /home/mininet/.ssh/id_rsa.pub | \
+          sudo -u mininet tee --append /home/mininet/.ssh/authorized_keys; done                        	# adicionando a chave do usuário mininet no authorized_keys (var_qtd_hosts)
 
     printf '\n\e[1;33m%-6s\e[m\n' 'Changing hostnames keys in authorized_keys'
     for i in $(cat -n /home/mininet/.ssh/authorized_keys | awk '{print $1}'); \
@@ -102,8 +123,9 @@ function ssh_file() {
 
 function node_file() {
     printf '\n\e[1;33m%-6s\e[m\n' '-- Creating configuration file for all cluster nodes...'
-    rm node*.sh												# apagando os arquivos de configuracao previos
-    for ((i=1; i<=$qtd_hosts; i++)); do echo "hostnamectl set-hostname node"$i"; echo \
+    rm -rf nodes											# apagando os arquivos de configuracao previos
+    mkdir nodes
+    for ((i=1; i<=$var_qtd_hosts; i++)); do echo "hostnamectl set-hostname node"$i"; echo \
           '\nallow-hotplug eth1\niface eth1 inet static\naddress 10.0.0.$i\nnetmask 255.255.255.0' \
           >> /etc/network/interfaces" >> node$i.sh; chmod 755 node$i.sh; done
     printf '\n%s\n' 'showing nodes file'
@@ -112,35 +134,35 @@ function node_file() {
 
 function install_mininet() {
     printf '\n\e[1;33m%-6s\e[m\n' '-- Installing Mininet 2.2.2...'
-    cd /usr/src
-    git clone git://github.com/mininet/mininet
-    cd mininet
+    git clone git://github.com/mininet/mininet $BUILD_DIR
+    cd $BUILD_DIR/mininet
     git tag
     git checkout -b 2.2.2 2.2.2
-    cd ..
     printf '\n\e[1;33m%-6s\e[m\n' 'Fixing iproute Mininet issue (using iproute2)'
     sed -i -- 's/iproute/iproute2/g' /usr/src/mininet/util/install.sh
-    mininet/util/install.sh -a
+    $BUILD_DIR/mininet/util/install.sh -a
     printf '\n\e[1;33m%-6s\e[m\n' 'Testing Mininet'
     mn --test pingall
 }
 
+function install_app_nps() {
+    printf '\n\e[1;32m%-6s\e[m\n' '-- Installing Network Prototype Simulator (NPS)...'
+    printf '\n\e[1;33m%-6s\e[m\n' 'Resolving requirements'
+    apt install python-networkx python-matplotlib python-paramiko -y
+    apt install cmake default-jdk git ant libgl1-mesa-dev freeglut3-dev libgstreamer1.0-dev libgstreamermm-1.0-dev libwebkitgtk-dev -y
+    apt autoremove -y
+    printf '\n\e[1;33m%-6s\e[m\n' 'Installing NPS in /usr/src/nps'
+    git clone git://github.com/ARCCN/nps $BUILD_DIR
+    cp $BUILD_DIR/nps/config/services.py $BUILD_DIR/mininet/mininet
+    cp $BUILD_DIR/nps/config/services.py $BUILD_DIR/mininet/build/lib.linux-x86_64-2.7/mininet
+}
 
-# instalando o Network Prototype Simulator (NPS)
-
-###cd /usr/src
-###git clone git://github.com/ARCCN/nps
-###cp nps/config/services.py /usr/src/mininet/mininet
-###cp nps/config/services.py /usr/src/mininet/build/lib.linux-x86_64-2.7/mininet
-
-###apt install python-networkx python-matplotlib python-paramiko -y
-###apt install cmake default-jdk git ant libgl1-mesa-dev freeglut3-dev libgstreamer1.0-dev libgstreamermm-1.0-dev libwebkitgtk-dev -y
-###apt autoremove -y
-
+# set up build directory
+BUILD_DIR='/home/mininet/'
 
 welcome;
 qtd_hosts;
-#note;
+install_packages;
 update_SO_install_packages;
 network_configuration;
 user;
@@ -148,3 +170,18 @@ hosts_file;
 ssh_file;
 node_file;
 install_mininet;
+if [ "$var_app_nps" = "Y" ] || [ "$var_app_nps" = "y" ] ; then
+    install_app_nps;
+fi
+
+printf '\n\e[1;32m%-6s\e[m\n' ' ------------ FINISHED ------------ '
+printf '\n%s\n' 'Please, look for any trouble during installation process.' \
+                      'You requested installation of the following applications:' \
+		      ' - Mininet 2.2.2'
+if [ "$var_app_nps" = "Y" ] || [ "$var_app_nps" = "y" ] ; then
+    printf '%s\n' ' - Network Prototype Simulator (NPS)'
+fi
+
+if [ "$var_app_maxinet" = "Y" ] || [ "$var_app_maxinet" = "y" ] ; then
+    printf '%s\n' ' - MaxiNet'
+fi
